
[Villagers]
	#Wearing a Dark Helm and Robe, along with variants, causes Villagers around the Player to have a negative Reputation unless said Player has 100 or more reputation among them, Default: false
	villagerHate = false
	#Villagers have a chance of converting into Warlocks if they're underneath a Block of Crying Obsidian, Default: true
	villagerConvertToWarlock = true
	#Casting Spell in the presence of Villagers will cause the Player to lose a number of Reputation, set 0 to disable, Default: 0
	#Range: > 0
	villagerHateSpells = 0

["Soul Taken"]
	#Non-Undead Piglin Killed, Default: 10
	#Range: > 0
	piglinSouls = 10
	#Players Killed, Default: 100
	#Range: > 0
	playerSouls = 100
	#Ender Dragon Killed, Default: 1000
	#Range: > 0
	enderDragonSouls = 1000
	#Others Killed, Default: 5
	#Range: > 0
	otherSouls = 5
	#Anthropods Killed, Default: 5
	#Range: > 0
	anthropodSouls = 5
	#Villagers Killed, Default: 100
	#Range: > 0
	villagerSouls = 100
	#Warden Killed, Default: 10000
	#Range: > 0
	wardenSouls = 10000
	#Illagers, Witches, Cultists Killed, Default: 25
	#Range: > 0
	illagerSouls = 25
	#Undead Killed, Default: 5
	#Range: > 0
	undeadSouls = 5

[Lich]
	#Undead Mobs will not attack you if you're a Lich and will even defend you if you're attack by another mob and wearing the Necro Set, Default: true
	lichUndeadFriendly = true
	#How much Soul Energy is cost to heal the Player per second if they've become a Lich, Default: 1
	#Range: > 0
	lichHealCost = 1
	#Whether the player needs to read a Forbidden Scroll to start the Potion of Transformation ritual, Default: true
	lichScrollRequirement = true
	#If Lich Undead Friendly is set to true, Only undead that have lower than 50 Hearts are friendly, Default: true
	lichPowerfulHostile = true
	#Enable to make Liches 85% more resistant to Magic Attacks, Default: false
	lichMagicResist = false
	#Enable to get infinite Night Vision when being a Lich. If set true, wearing Fel Helm will no longer give Blindness during day, Default: true
	lichNightVision = true

[Mobs]
	#Whether Goety Mobs can spawn in Overworld-like modded dimensions, Default: false
	interDimensionalMobs = false
	#Whether Wraiths should teleport towards their targets if they can't see them instead of just teleporting away when they're near them, Default: true
	wraithAggressiveTeleport = true
	#Whether Mobs with Tall Heads(ie. Villagers, Illagers, etc.) will drop Tall Skulls, Default: true
	tallSkullDrop = true
	#Gives Apostle an even more fancier death animation, Default: false
	fancierApostleDeath = false
	#Spawn Weight for Wraith, Default: 20
	#Range: > 0
	wraithSpawnWeight = 20
	#Viziers spawn Vexes instead of Irks, Default: false
	vizierMinion = false
	#Spawn Weight for Warlock, Default: 5
	#Range: > 0
	warlockSpawnWeight = 5

[General]
	#Arca will save the Player if past Totem Maximum Soul Count, Default: true
	arcaUndying = true
	#Totem of Souls will save the Player if full of Soul Energy and its in Curio Slot or inventory, Default: true
	totemUndying = true
	#Certain Items repair themselves using Soul Energy, Default: true
	soulRepair = true
	#How much Souls is consumed when crafting with Totem, Default: 1
	#Range: > 0
	craftSouls = 1
	#Gives Players a Totem of Souls when first entering World, Default: false
	starterTotem = false
	#Bosses from the Mod has custom Music Playing. Default: true
	bossMusic = true
	#Vertical Position of where the Soul Energy Bar is located, Default: -5
	#Range: > -2147483647
	soulGuiVertical = -5
	#Horizontal Position of where the Soul Energy Bar is located, Default: 100
	#Range: > -2147483647
	soulGuiHorizontal = 100
	#Show the Soul Energy Bar if Player has Totem of Souls/Arca, Default: true
	soulGuiShow = true
	#Gives Players the Black Book when first entering World and Patchouli is loaded, Default: false
	starterBook = false
	#Show numerical amount of Souls on the Soul Energy Bar, Default: false
	showNumber = false
	#Show gloves in first person, Default: true
	firstPersonGloves = true
	#Nether Meteors deals environmental damage. WARNING: Causes lots of lag. Default: false
	apocalypseMode = false
	#Bosses from the Mod has custom looking Boss Bars. Default: true
	specialBossBar = true
	#Totem Maximum Soul Count and Threshold to save the Player, Default: 10000
	#Range: > 10
	maxSouls = 10000
	#Arca Maximum Soul Count, Default: 100000
	#Range: > 10
	maxArcaSouls = 100000

[Items]
	#How much Soul Energy is taken per second when wearer is falling slowly, Default: 1
	#Range: > 1
	windRobeSouls = 1
	#Amount of Souls needed to repair certain Equipments per second, Default: 5
	#Range: > 1
	darkArmoredRobeRepairSouls = 5
	#Render Wind Robe Cape, Default: true
	windRobeCape = true
	#Scythe Slashes from Death Scythe breaks blocks that regular Scythes easily breaks, Default: true
	scytheSlashBreaks = true
	#Amount of Soul Energy Dark Scythe gives when hitting mob(s), Default: 1
	#Range: > 1
	darkScytheSouls = 1

["Tools & Weapons"]
	#How much damage Death Scythe deals, the configured number is added to Scythe Base Damage, Default: 4.0
	#Range: 1.0 ~ 1.7976931348623157E308
	deathScytheDamage = 4.0
	#How much base damage Nameless Staffs deals, Default: 6.0
	#Range: 1.0 ~ 1.7976931348623157E308
	namelessStaffDamage = 6.0
	#How much base damage Necro Staffs deals, Default: 4.0
	#Range: 1.0 ~ 1.7976931348623157E308
	necroStaffDamage = 4.0
	#How many uses before Death Scythe breaks, Default: 444
	#Range: > 1
	deathScytheDurability = 444
	#How fast it takes to fully swing a Scythe with item offhand and not wearing Grave Gloves. The lower the number the slower it takes to recharge, Default: 0.6
	#Range: 0.0 ~ 1.7976931348623157E308
	scytheAttackSpeed = 0.6
	#How much damage Philosopher's Mace deals, Default: 9.0
	#Range: 1.0 ~ 1.7976931348623157E308
	philosophersMaceDamage = 9.0
	#How much base damage Scythes deals, the damage added depends on material the scythe is made off (ie. Iron = 2.0), Default: 5.5
	#Range: 1.0 ~ 1.7976931348623157E308
	scytheBaseDamage = 5.5
	#Define the Enchantability for Death Scythe, higher number the better, Default: 22
	#Range: > 1
	deathScytheEnchantability = 22
	#How much base damage Wind Staffs deals, Default: 4.0
	#Range: 1.0 ~ 1.7976931348623157E308
	windStaffDamage = 4.0
	#How many uses before the Philosopher's Mace breaks, Default: 128
	#Range: > 1
	philosophersMaceDurability = 128

[Illagers]
	#Spawn Frequency for Illagers Hunting the Player, Default: 12000
	#Range: > 0
	illagerAssaultSpawnFreq = 12000
	#Whether Enviokers, Inquillagers and Conquillagers can steal Totems of Souls or Totems of Undying, Default: true
	illagerSteal = true
	#Whether Enviokers, Inquillagers and Conquillagers can join Raids, Default: true
	specialIllagerRaid = true
	#The maximum amount of Soul Energy the Player has that is taken consideration for the Assaults, Default: 30000
	#Range: > 0
	illagerAssaultLimit = 30000
	#Spawn Chance for Illagers Hunting the Player every Infamy Spawn Frequency, the lower the more likelier, Default: 5
	#Range: > 0
	illagerAssaultSpawnChance = 5
	#Whether Illague Effect can spread from non Conquillagers that has the effect, Default: true
	illagueSpread = true
	#Hitting the Illager Assault Limit of Soul Energy have a chance of giving Player Bad Omen effect, Default: true
	soulEnergyBadOmen = true
	#Special Illagers Spawning based of Player's Soul Energy amount, Default: true
	illagerAssault = true
	#How much Soul Energy the Player has is required for Special Illagers to spawn, Default: 2500
	#Range: > 0
	illagerAssaultThreshold = 2500

